require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SnacksController do

  def mock_snack(stubs={})
    @mock_snack ||= mock_model(Snack, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all snacks as @snacks" do
      Snack.stub(:all) { [mock_snack] }
      get :index
      assigns(:snacks).should eq([mock_snack])
    end
  end

  describe "GET show" do
    it "assigns the requested snack as @snack" do
      Snack.stub(:find).with("37") { mock_snack }
      get :show, :id => "37"
      assigns(:snack).should be(mock_snack)
    end
  end

  describe "GET new" do
    it "assigns a new snack as @snack" do
      Snack.stub(:new) { mock_snack }
      get :new
      assigns(:snack).should be(mock_snack)
    end
  end

  describe "GET edit" do
    it "assigns the requested snack as @snack" do
      Snack.stub(:find).with("37") { mock_snack }
      get :edit, :id => "37"
      assigns(:snack).should be(mock_snack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created snack as @snack" do
        Snack.stub(:new).with({'these' => 'params'}) { mock_snack(:save => true) }
        post :create, :snack => {'these' => 'params'}
        assigns(:snack).should be(mock_snack)
      end

      it "redirects to the created snack" do
        Snack.stub(:new) { mock_snack(:save => true) }
        post :create, :snack => {}
        response.should redirect_to(snack_url(mock_snack))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved snack as @snack" do
        Snack.stub(:new).with({'these' => 'params'}) { mock_snack(:save => false) }
        post :create, :snack => {'these' => 'params'}
        assigns(:snack).should be(mock_snack)
      end

      it "re-renders the 'new' template" do
        Snack.stub(:new) { mock_snack(:save => false) }
        post :create, :snack => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested snack" do
        Snack.stub(:find).with("37") { mock_snack }
        mock_snack.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :snack => {'these' => 'params'}
      end

      it "assigns the requested snack as @snack" do
        Snack.stub(:find) { mock_snack(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:snack).should be(mock_snack)
      end

      it "redirects to the snack" do
        Snack.stub(:find) { mock_snack(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(snack_url(mock_snack))
      end
    end

    describe "with invalid params" do
      it "assigns the snack as @snack" do
        Snack.stub(:find) { mock_snack(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:snack).should be(mock_snack)
      end

      it "re-renders the 'edit' template" do
        Snack.stub(:find) { mock_snack(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested snack" do
      Snack.stub(:find).with("37") { mock_snack }
      mock_snack.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the snacks list" do
      Snack.stub(:find) { mock_snack }
      delete :destroy, :id => "1"
      response.should redirect_to(snacks_url)
    end
  end

end
